# Firefly Common Data Library - Default Configuration
firefly:
  data:
    eda:
      enabled: true
    cqrs:
      enabled: true
    orchestration:
      enabled: true
    transactional:
      enabled: true
  stepevents:
    enabled: true
    topic: data-processing-step-events
    include-job-context: true