# Example configuration for Firefly Common Data Library - Job Orchestration
# This file demonstrates how to configure job orchestration for core-data microservices

firefly:
  data:
    # EDA (Event-Driven Architecture) Configuration
    eda:
      enabled: true
      
    # CQRS Configuration
    cqrs:
      enabled: true
      
    # Job Orchestration Configuration
    orchestration:
      enabled: true
      orchestrator-type: AWS_STEP_FUNCTIONS
      default-timeout: 24h
      max-retries: 3
      retry-delay: 5s
      publish-job-events: true
      job-events-topic: data-job-events
      
      # AWS Step Functions specific configuration
      aws:
        region: us-east-1
        state-machine-arn-prefix: arn:aws:states:us-east-1:123456789012:stateMachine
        use-default-credentials: true
        
    # Transactional Engine Configuration
    transactional:
      enabled: true
      
  # Step Events Configuration (for SAGA support)
  stepevents:
    enabled: true
    # Separate topic for data processing step events
    topic: data-processing-step-events
    # Include job context in step event headers for traceability
    include-job-context: true

# EDA Publisher Configuration (from lib-common-eda)
# Uncomment and configure based on your messaging infrastructure
#firefly:
#  eda:
#    publishers:
#      - id: default
#        type: KAFKA
#        connection-id: default
#        enabled: true
#    connections:
#      kafka:
#        - id: default
#          bootstrap-servers: localhost:9092
#          enabled: true

# Example for AWS SQS
#      - id: default
#        type: SQS
#        connection-id: default
#        enabled: true
#    connections:
#      sqs:
#        - id: default
#          region: us-east-1
#          enabled: true
